src/Entity/Items.php
<?php

namespace App\Entity;

use App\Repository\ItemsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=ItemsRepository::class)
 */
class Items
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $categories;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="bigint")
     */
    private $amount;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $purchasing_value;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $sales_value;

    /**
     * @ORM\Column(type="integer")
     */
    private $alertValue;

    /**
     * @ORM\ManyToMany(targetEntity=ReservationItem::class, inversedBy="items")
     */
    private $reservation_item;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creationDate;

    public function __construct()
    {
        $this->reservation_item = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategories(): ?string
    {
        return $this->categories;
    }

    public function setCategories(?string $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPurchasingValue(): ?string
    {
        return $this->purchasing_value;
    }

    public function setPurchasingValue(string $purchasing_value): self
    {
        $this->purchasing_value = $purchasing_value;

        return $this;
    }

    public function getSalesValue(): ?string
    {
        return $this->sales_value;
    }

    public function setSalesValue(string $sales_value): self
    {
        $this->sales_value = $sales_value;

        return $this;
    }

    public function getAlertValue(): ?int
    {
        return $this->alertValue;
    }

    public function setAlertValue(int $alertValue): self
    {
        $this->alertValue = $alertValue;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * @return Collection<int, reservationitem>
     */
    public function getReservationItem(): Collection
    {
        return $this->reservation_item;
    }

    public function addReservationItem(reservationitem $reservationItem): self
    {
        if (!$this->reservation_item->contains($reservationItem)) {
            $this->reservation_item[] = $reservationItem;
        }

        return $this;
    }

    public function removeReservationItem(reservationitem $reservationItem): self
    {
        $this->reservation_item->removeElement($reservationItem);

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();

    }
}

src/Form/ItemsType.php
<?php

namespace App\Form;

use App\Entity\Items;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class ItemsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('categories')
            ->add('description')
            ->add('amount', NumberType::class,[
            'label' => 'quantity',])
            ->add('purchasing_value')
            ->add('sales_value')
            ->add('alertValue')
            ->add('creationDate', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker']])
            ->add('save', SubmitType::class, [
            'attr' =>['class' => 'save'],
                ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Items::class,
        ]);
    }
}

src/Controller/ItemsController.php
<?php

namespace App\Controller;

use App\Entity\Items;
use App\Form\ItemsType;
use App\Repository\ItemsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/items')]
class ItemsController extends AbstractController
{
    #[Route('/', name: 'app_items_index', methods: ['GET', 'POST'])]
    public function index(ItemsRepository $itemsRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('items/index.html.twig', [
            'items' => $itemsRepository->findAll(),

        ]);

    }

    #[Route('/new', name: 'app_items_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ItemsRepository $itemsRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $item = new Items();
        $item->setCreationDate(new \DateTime());
        dump($item->getCreationDate());
        $form = $this->createForm(ItemsType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemsRepository->add($item, true);
            $this->addFlash('success' , 'item has been added to the database!');
            return $this->redirectToRoute('app_items_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('items/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }
    
    #[Route('/{id}/edit', name: 'app_items_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Items $item, ItemsRepository $itemsRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(ItemsType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemsRepository->add($item, true);

            return $this->redirectToRoute('app_items_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('items/edit.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_items_delete', methods: ['POST'])]
    public function delete(Request $request, Items $item, ItemsRepository $itemsRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$item->getId(), $request->request->get('_token'))) {
            $itemsRepository->remove($item, true);
        }

        return $this->redirectToRoute('app_items_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/items/_delete_form.html.twig
<form method="post" action="{{ path('app_items_delete', {'id': item.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/items/_form.html.twig
<div class="container-fluid">
    <table class="table">
        <tbody>
        <tr>
            {{ form_start(form) }}
            <td>{{ form_row(form.name) }}</td>
        </tr>
        <tr>
            <td>{{ form_row(form.categories) }}</td>
        </tr>
        <tr>
            <td>{{ form_row(form.description) }}</td>
        </tr>
        <tr>
            <td>{{ form_row(form.amount) }}</td>
        </tr>
        <tr>
            <td>{{ form_row(form.purchasing_value) }}</td>
        </tr>
        <tr>
            <td>{{ form_row(form.sales_value) }}</td>
        </tr>
        <tr>
        </tr>
        <td>{{ form_row(form.alertValue) }}</td>
        <tr>
            <td>
                <button class="btn btn-success"
                {{ form_widget(form.save) }}</button></td>
        </tr>
        {{ form_end(form) }}
        </tbody>
    </table>
</div>

templates/items/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Items{% endblock %}

{% block body %}
    <div class="container-fluid">
    <h1>Edit Items</h1>

    {{ include('items/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('app_items_index') }}">back to list</a>

    {{ include('items/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/items/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Items index{% endblock %}

{% block body %}
    <div class="container">
        <h2>Items index</h2>
        <hr>
        <a class="btn btn-success" href="{{ path('app_items_new') }}">Create new</a>
        <hr>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Categories</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Purchasing_value</th>
                <th>Sales_value</th>
                <th>Datum</th>
                <th>AlertValue</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.categories }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.amount }}</td>
                    <td>€{{ item.purchasingValue|number_format(2, ',', '.') }}</td>
                    <td>€{{ item.salesValue|number_format(2, ',', '.') }}</td>
                    <td>{{ item.creationDate ? item.creationDate|date('Y-m-d') : 'datepicker' }}</td>
                    <td>{{ item.alertValue }}</td>
                    <td>
                        {{ include('items/_delete_form.html.twig') }}

                        <a class="btn btn-warning" href="{{ path('app_items_edit', {'id': item.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/items/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Items{% endblock %}

{% block body %}
    <div class="container">
        <h1>Create new Items</h1>

        {{ include('items/_form.html.twig') }}

        <a class="btn btn-primary" href="{{ path('app_items_index') }}">back to list</a>
    </div>
{% endblock %}